In [107]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [108]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [109]:
scalar.ndim

0

In [110]:
scalar.item()

7

In [111]:
vector = torch.tensor((7,7))
vector

tensor([7, 7])

In [112]:
vector.ndim

1

In [113]:
vector.shape

torch.Size([2])

In [114]:
MATRIX = torch.tensor([[7,8], 
                      [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [115]:
MATRIX.ndim

2

In [116]:
MATRIX[0]

tensor([7, 8])

In [117]:
MATRIX.shape

torch.Size([2, 2])

In [118]:
TENSOR = torch.tensor([[[1,2,3],
                        [3, 6, 9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [119]:
TENSOR.ndim

3

In [120]:
TENSOR.shape

torch.Size([1, 3, 3])

In [121]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tansor

In [122]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7035, 0.6581, 0.4015, 0.1583],
        [0.5292, 0.2914, 0.1814, 0.6955],
        [0.3169, 0.2110, 0.0047, 0.9624]])

In [123]:
random_tensor.ndim

2

In [124]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [125]:
torch.rand(3,3)

tensor([[0.5179, 0.6721, 0.2251],
        [0.4025, 0.4610, 0.0799],
        [0.2187, 0.3449, 0.9264]])

Zero and Ones

In [126]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [127]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [128]:
ones.dtype

torch.float32

Range and Tensor like

In [129]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [130]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros  

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [131]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [132]:
float_32_tensor.dtype

torch.float32

In [133]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [134]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [135]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [136]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [137]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0773, 0.3436, 0.4741, 0.9290],
        [0.5862, 0.7057, 0.8028, 0.8803],
        [0.2378, 0.4648, 0.8388, 0.1517]])

In [138]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [139]:
print(some_tensor)
print(f'datatypes of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(f'device tensor is on: {some_tensor.device}')

tensor([[0.0773, 0.3436, 0.4741, 0.9290],
        [0.5862, 0.7057, 0.8028, 0.8803],
        [0.2378, 0.4648, 0.8388, 0.1517]])
datatypes of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
device tensor is on: cpu


Manipulating Tensors 

In [140]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [141]:
tensor * 10

tensor([10, 20, 30])

In [142]:
tensor

tensor([1, 2, 3])

In [143]:
tensor - 10

tensor([-9, -8, -7])

In [144]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [145]:
torch.add(tensor, 10)

tensor([11, 12, 13])

Matrix Multiplication

In [146]:
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [147]:
torch.matmul(tensor, tensor)

tensor(14)

In [148]:
tensor

tensor([1, 2, 3])

In [149]:
1*1 + 2*2 + 3*3

14

In [150]:
%%time
value = 0
for i in range(len(tensor)): 
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 479 µs, sys: 1.11 ms, total: 1.59 ms
Wall time: 1.94 ms


Jika Dibandingkan Dengan diatas dan dibawah ini, lebih cepat menggunakan function dari pytorch lihat Cpu Times dan Wall Time dalam perhitungan Matriks Multiplier

In [151]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 279 µs, sys: 0 ns, total: 279 µs
Wall time: 219 µs


tensor(14)

In [152]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.matmul(tensor_A, tensor_B)

In [153]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

BTW Error diatas di sengaja karena Matriks tidak bisa jika Shape nya sama Maka Kita Gunakan **tanspose** you know lah di kalkulus what that mean, dibalik T

In [154]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [155]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Mencari min, max, mean, sum dll di tensor aggregation

In [156]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [157]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [158]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [159]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Mencari posisi Min Max dengan Arg

In [160]:
x.argmin()

tensor(0)

In [161]:
x.argmax()

tensor(9)

In [162]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

Reshaping , stacking , squeezing and unaqueezing

In [163]:
x = torch.arange(1., 10.)
x , x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [164]:
# add extra demension

x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [165]:
# change view

z = x.view(1,9)
z, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([9]))

In [166]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [167]:
# remove single dimmesion (array coba perhatikan perbedaan tanpa squezee)
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [190]:
x_reshape.unsqueeze(dim=0)

tensor([[[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [169]:
x_original = torch.rand(244, 244, 3)

x_permuted = x_original.permute(2, 0, 1)

x_permuted

tensor([[[0.4514, 0.3442, 0.9520,  ..., 0.1743, 0.1002, 0.7192],
         [0.8983, 0.0225, 0.5496,  ..., 0.1528, 0.0403, 0.9641],
         [0.5198, 0.1241, 0.2013,  ..., 0.0724, 0.3877, 0.6209],
         ...,
         [0.7555, 0.6439, 0.4668,  ..., 0.0120, 0.0373, 0.5594],
         [0.9305, 0.5607, 0.5063,  ..., 0.8580, 0.7392, 0.1264],
         [0.5900, 0.9157, 0.7781,  ..., 0.1096, 0.3853, 0.9143]],

        [[0.9856, 0.4321, 0.3286,  ..., 0.4076, 0.6201, 0.0130],
         [0.5874, 0.0622, 0.5431,  ..., 0.3006, 0.0351, 0.4768],
         [0.7731, 0.6098, 0.4280,  ..., 0.8873, 0.7802, 0.3715],
         ...,
         [0.8548, 0.3054, 0.8221,  ..., 0.7228, 0.5012, 0.6722],
         [0.9586, 0.5478, 0.2128,  ..., 0.9643, 0.5264, 0.9343],
         [0.0031, 0.1638, 0.7627,  ..., 0.0108, 0.5477, 0.4606]],

        [[0.6651, 0.3880, 0.0019,  ..., 0.1971, 0.9209, 0.0191],
         [0.4237, 0.1316, 0.1402,  ..., 0.8454, 0.9330, 0.0968],
         [0.6158, 0.2036, 0.8096,  ..., 0.1406, 0.3636, 0.

In [170]:
x_original[0,0,0] = 728118
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728118.), tensor(728118.))

In [171]:
import torch

x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [172]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [173]:
x[0][0]

tensor([1, 2, 3])

In [174]:
x[0][2][2]

tensor(9)

In [175]:
x[:, 0]

tensor([[1, 2, 3]])

In [176]:
x[:, :, 2]

tensor([[3, 6, 9]])

Tensor & Numpy

In [177]:
import torch
import numpy as np

array = np.arange(1, 10)
tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

Trying to take random out of random

In [178]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8135, 0.4042, 0.4185, 0.6799],
        [0.8438, 0.8496, 0.4808, 0.3289],
        [0.0132, 0.0174, 0.3129, 0.4653]])
tensor([[0.9445, 0.0221, 0.0236, 0.2313],
        [0.6510, 0.5777, 0.8961, 0.1800],
        [0.0498, 0.9551, 0.1908, 0.1360]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [179]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [180]:
!nvidia-smi

Thu Jul 16 07:11:56 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   65C    P0             29W /   70W |     109MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [181]:
torch.cuda.is_available()

True

In [182]:
torch.cuda.device_count()

1