In [12]:
import torch

In [13]:
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

tensor1, tensor2

(tensor([[0.4010, 0.4676, 0.0318, 0.6105, 0.3547, 0.8168, 0.0232],
         [0.5873, 0.0607, 0.1095, 0.8718, 0.1899, 0.9860, 0.5584],
         [0.9167, 0.0011, 0.5662, 0.0840, 0.7362, 0.5715, 0.9331],
         [0.3924, 0.7878, 0.7870, 0.6370, 0.0047, 0.7834, 0.5338],
         [0.2813, 0.6669, 0.1597, 0.8496, 0.6184, 0.7659, 0.1521],
         [0.6724, 0.4869, 0.6527, 0.6737, 0.6999, 0.4616, 0.1849],
         [0.9827, 0.7978, 0.1949, 0.1817, 0.0637, 0.3072, 0.3074]]),
 tensor([[0.7783, 0.8161, 0.3866, 0.8584, 0.8891, 0.4283, 0.2895]]))

In [35]:
# tensor 2 change to Tranpose because matriks rand shape 1, 7 not compatible for 7 x 7
tensor2 = tensor2.T

tensor2

tensor([[0.6289],
        [0.9653],
        [0.0673],
        [0.8007],
        [0.2284],
        [0.0849],
        [0.9831]])

In [38]:
tensorMulti = torch.matmul(tensor1, tensor2)

tensorMulti

tensor([[1.4971],
        [1.5773],
        [1.5726],
        [1.4702],
        [1.8245],
        [2.3666],
        [1.8968]])

In [17]:
torch.cuda.is_available()

True

In [39]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

tensor1, tensor2

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]))

In [33]:
tensorMulti = torch.matmul(tensor1, tensor2.T)
tensorMulti

tensor([[1.4971],
        [1.5773],
        [1.5726],
        [1.4702],
        [1.8245],
        [2.3666],
        [1.8968]])

GPU Tensor

In [76]:
device = "cuda"
RANDOM_SEED_GPU = 1234

torch.cuda.manual_seed(RANDOM_SEED_GPU)
tensor_gpu1 = torch.rand(2,3, device=device)
tensor_gpu2 = torch.rand(2,3, device=device)

tensor_gpu1, tensor_gpu2
print(tensor_gpu1.device)

cuda:0


In [44]:
tensorMulti_GPU = torch.matmul(tensor_gpu1, tensor_gpu2.T)
tensorMulti_GPU

tensor([[1.7488, 0.6094],
        [1.4999, 0.5721]])

In [48]:
print(f'Tensor Terkecil : {torch.min(tensorMulti_GPU)}')
print(f'Posisi Terkecil : {torch.argmin(tensorMulti_GPU)}')
print(f'Tensor Terbesar : {torch.max(tensorMulti_GPU)}')
print(f'Posisi Terbesar : {torch.argmax(tensorMulti_GPU)}')

Tensor Terkecil : 0.5720946788787842
Posisi Terkecil : 3
Tensor Terbesar : 1.7488125562667847
Posisi Terbesar : 0


In [70]:

torch.manual_seed(7)
dimension = torch.rand(1,1,1,10)

torch.cuda.manual_seed(7)
dimension_squeeze = torch.squeeze(dimension)

dimension, dimension_squeeze

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))

In [71]:
print(f'Sebelum Diubah : {dimension.shape}')
print(f'Setelah Diubah : {dimension_squeeze.shape}')

Sebelum Diubah : torch.Size([1, 1, 1, 10])
Setelah Diubah : torch.Size([10])
